# Generated by Django 4.2.7 on 2026-05-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocateprofile",
            name="bar_council_id",
            field=models.CharField(
                blank=True, default=None, max_length=100, null=True, unique=True
            ),
        ),
    ]
