# Generated by Django 4.2.7 on 2026-05-17 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_advocateprofile_bar_council_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("post_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hashtags",
                "ordering": ["-post_count"],
            },
        ),
        migrations.CreateModel(
            name="LegalUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "legal_updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="advocateprofile",
            name="group_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advocateprofile",
            name="media_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="advocateprofile",
            name="message_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="channel",
            name="pinned_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="accent_color",
            field=models.CharField(default="blue", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="advocate_rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="user",
            name="cases_handled",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="notif_calls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notif_group_mentions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notif_messages",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notif_stories",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="presence_status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("away", "Away"),
                    ("offline", "Offline"),
                ],
                default="offline",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_last_seen",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_online_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_read_receipts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Dark"), ("light", "Light")],
                default="dark",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("message", "New Message"),
                    ("connection_request", "Connection Request"),
                    ("connection_accepted", "Connection Accepted"),
                    ("channel_update", "Channel Update"),
                    ("mention", "Mention"),
                    ("reply", "Reply"),
                    ("reaction", "Post Reaction"),
                    ("comment", "Comment"),
                    ("verification_approved", "Verification Approved"),
                    ("verification_rejected", "Verification Rejected"),
                    ("follow", "New Follower"),
                    ("post", "New Post"),
                    ("hearing_reminder", "Hearing Reminder"),
                    ("legal_update", "Legal Update"),
                    ("system", "System"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("legal_update", "Legal Update"),
                    ("court_news", "Court News"),
                    ("media", "Media Post"),
                    ("article", "Article"),
                    ("judgment", "Judgment"),
                    ("document", "Document"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SubChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_channels",
                        to="api.channel",
                    ),
                ),
            ],
            options={
                "db_table": "sub_channels",
                "ordering": ["name"],
                "unique_together": {("parent", "slug")},
            },
        ),
        migrations.CreateModel(
            name="PostShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="api.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "post_shares",
            },
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("case_title", models.CharField(max_length=300)),
                ("case_number", models.CharField(blank=True, max_length=100)),
                ("court", models.CharField(max_length=200)),
                ("court_room", models.CharField(blank=True, max_length=100)),
                ("hearing_time", models.TimeField()),
                ("hearing_date", models.DateField()),
                (
                    "hearing_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("virtual", "Virtual"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="physical",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "advocate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hearings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hearings",
                "ordering": ["hearing_date", "hearing_time"],
            },
        ),
        migrations.AddField(
            model_name="channelpost",
            name="sub_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="api.subchannel",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="api.hashtag"
            ),
        ),
        migrations.CreateModel(
            name="SavedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="api.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_posts",
                "unique_together": {("user", "post")},
            },
        ),
    ]
