# Generated by Django 4.2.7 on 2026-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_hashtag_legalupdate_advocateprofile_group_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocateprofile",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="advocateprofile",
            name="primary_court",
            field=models.CharField(
                blank=True,
                choices=[
                    ("supreme_court", "Supreme Court of India"),
                    ("high_court", "High Court"),
                    ("district_court", "District Court"),
                    ("family_court", "Family Court"),
                    ("consumer_court", "Consumer Court"),
                    ("tribunal", "Tribunal"),
                    ("sessions_court", "Sessions Court"),
                    ("magistrate_court", "Magistrate Court"),
                    ("civil_court", "Civil Court"),
                    ("revenue_court", "Revenue Court"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
