# Generated by Django 4.2.7 on 2026-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_advocateprofile_onboarding_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocateprofile",
            name="profile_photo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
