# Generated by Django 4.2.7 on 2026-05-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_advocateprofile_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
