# Generated by Django 4.2.7 on 2026-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_message_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("pdf", "PDF Document"),
                    ("doc", "Word Document"),
                    ("voice", "Voice Note"),
                    ("file", "File"),
                    ("system", "System Message"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
