# Generated by Django 4.2.7 on 2026-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_message_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
