# Generated by Django 4.2.7 on 2026-05-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_post_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending Approval"),
                    ("banned", "Banned"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
