# Generated by Django 4.2.7 on 2026-05-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_channelmembership_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="cover",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="icon",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
