# Generated by Django 4.2.7 on 2026-05-31 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_channel_cover_alter_channel_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channelpost",
            name="attachment",
        ),
        migrations.AddField(
            model_name="channelpost",
            name="attachment_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name="ChannelPostReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "👍 Like"),
                            ("love", "❤️ Love"),
                            ("insightful", "💡 Insightful"),
                            ("celebrate", "🎉 Celebrate"),
                            ("support", "🤝 Support"),
                        ],
                        default="like",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="api.channelpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_post_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "channel_post_reactions",
                "unique_together": {("post", "user")},
            },
        ),
    ]
