# Generated by Django 4.2.7 on 2026-06-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_channelpost_attachment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subchannel",
            options={"ordering": ["-is_default", "created_at"]},
        ),
        migrations.AddField(
            model_name="subchannel",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
