# Generated by Django 4.2.7 on 2026-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_subchannel_options_subchannel_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocateprofile",
            name="cover_photo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
