# Generated by Django 4.2.7 on 2026-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="who_can_message",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("connections", "Connections Only"),
                    ("nobody", "Nobody"),
                ],
                default="connections",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="who_can_see_profile",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("connections", "Connections Only"),
                    ("nobody", "Nobody"),
                ],
                default="everyone",
                max_length=20,
            ),
        ),
    ]
