# Generated by Django 4.2.7 on 2026-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_user_who_can_message_user_who_can_see_profile"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "is_deleted", "-created_at"],
                name="msg_room_deleted_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["sender"], name="msg_sender_idx"),
        ),
    ]
