# Generated by Django 4.2.7 on 2026-06-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_message_msg_room_deleted_created_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocateprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="advocateprofile",
            index=models.Index(fields=["city"], name="profile_city_idx"),
        ),
        migrations.AddIndex(
            model_name="advocateprofile",
            index=models.Index(fields=["state"], name="profile_state_idx"),
        ),
        migrations.AddIndex(
            model_name="advocateprofile",
            index=models.Index(
                fields=["-connection_count"], name="profile_conn_count_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="advocateprofile",
            index=models.Index(fields=["years_of_experience"], name="profile_exp_idx"),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(
                fields=["channel_type", "-member_count"],
                name="channel_type_members_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="channel",
            index=models.Index(fields=["is_official"], name="channel_official_idx"),
        ),
        migrations.AddIndex(
            model_name="channelmembership",
            index=models.Index(
                fields=["user", "status"], name="chanmem_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelmembership",
            index=models.Index(
                fields=["channel", "user", "status"], name="chanmem_ch_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelpost",
            index=models.Index(
                fields=["channel", "-is_pinned", "-created_at"],
                name="chanpost_ch_pin_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="channelpost",
            index=models.Index(
                fields=["channel", "sub_channel", "-created_at"],
                name="chanpost_ch_sub_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="channelpostcomment",
            index=models.Index(
                fields=["post", "parent", "created_at"],
                name="chancomment_post_parent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="channelpostreaction",
            index=models.Index(fields=["post", "user"], name="chanreact_post_user_idx"),
        ),
        migrations.AddIndex(
            model_name="channelpostreaction",
            index=models.Index(
                fields=["post", "reaction_type"], name="chanreact_post_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["user", "room"], name="chatpart_user_room_idx"),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(fields=["room", "user"], name="chatpart_room_user_idx"),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["sender", "status"], name="conn_sender_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["receiver", "status"], name="conn_receiver_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["status", "sender", "receiver"], name="conn_status_both_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["follower", "following"], name="follow_follower_following_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(fields=["following"], name="follow_following_idx"),
        ),
        migrations.AddIndex(
            model_name="hearing",
            index=models.Index(
                fields=["advocate", "hearing_date"], name="hearing_advocate_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalupdate",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="legalupdate_active_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"],
                name="notif_recip_read_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["user", "purpose", "is_used"], name="otp_user_purpose_used_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="post_author_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_public", "-created_at"], name="post_public_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(
                fields=["post", "parent", "created_at"],
                name="postcomment_post_parent_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(fields=["post", "user"], name="postreact_post_user_idx"),
        ),
        migrations.AddIndex(
            model_name="savedpost",
            index=models.Index(fields=["user", "post"], name="savedpost_user_post_idx"),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["author", "expires_at"], name="story_author_expires_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_advocate"], name="user_active_advocate_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="user_phone_idx"),
        ),
    ]
