# Generated by Django 4.2.7 on 2026-07-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_advocateprofile_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipant",
            name="cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
